//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antarik_Basai_Sarai
    {
        public int FormId { get; set; }
        public string Aabedan_miti { get; set; }
        public string Purano_basobas_miti { get; set; }
        public string Aabedak_naam { get; set; }
        public string Buwako_naam { get; set; }
        public string Amako_naam { get; set; }
        public string Purano_Pradesh { get; set; }
        public string Purano_Jilla { get; set; }
        public string Purano_Gabisa { get; set; }
        public string Purano_Ward { get; set; }
        public string Purano_Tole { get; set; }
        public string Haal_Pradesh { get; set; }
        public string Haal_Jilla { get; set; }
        public string Haal_Gabisa { get; set; }
        public string Haal_Ward { get; set; }
        public string Haal_Tole { get; set; }
        public string Pariwaarko_naam { get; set; }
        public string Nata { get; set; }
        public string Nagarikta_janmadarta_no { get; set; }
        public string Ghar_no { get; set; }
        public string Batoko_naam { get; set; }
        public string Umer { get; set; }
    }
}
