//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anya_Sifaris
    {
        public int AnyaId { get; set; }
        public string Aabedak_naam { get; set; }
        public string Aabedan_miti { get; set; }
        public string Patrakokisim { get; set; }
        public string Patrakobisaya { get; set; }
        public string Freespace { get; set; }
    }
}
