//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Byawasaya_Banda_Barey
    {
        public int FormId { get; set; }
        public string Aabedan_miti { get; set; }
        public string Byawasaya_naam { get; set; }
        public string Byawasayi_naam { get; set; }
        public string Darta_no { get; set; }
        public string Prakaar { get; set; }
        public string Prakriti { get; set; }
        public string Pradesh { get; set; }
        public string Jilla { get; set; }
        public string Gabisa { get; set; }
        public string Ward { get; set; }
        public string Sabik_thegana { get; set; }
        public string Haal_thegana { get; set; }
        public string Toleko_naam { get; set; }
        public string Batoko_naam { get; set; }
        public string Gharno { get; set; }
        public string Byawasaya_Bandamiti { get; set; }
        public string Sarjamin_miti { get; set; }
        public string ImagePath { get; set; }
    }
}
