//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charkilla_Sambandhama
    {
        public int Form_Id { get; set; }
        public string Aabedan_miti { get; set; }
        public string Karyalaya { get; set; }
        public string Jaggadhaniko_naam { get; set; }
        public string Pradesh { get; set; }
        public string Jilla { get; set; }
        public string Gabisa { get; set; }
        public string Ward { get; set; }
        public string Sabik_gabisa { get; set; }
        public string Haal_gabisa { get; set; }
        public string Naksha_sheetno { get; set; }
        public string Kitta_no { get; set; }
        public string Bigga { get; set; }
        public string Kattha { get; set; }
        public string Dhur { get; set; }
        public string Batoko_Prakaar { get; set; }
        public string East { get; set; }
        public string West { get; set; }
        public string North { get; set; }
        public string South { get; set; }
        public string Kaifiyat { get; set; }
    }
}
