//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghar_kayamko_sifaris
    {
        public int FormId { get; set; }
        public string Aabedan_miti { get; set; }
        public string karyalaya { get; set; }
        public string Aabedak_name { get; set; }
        public string Pradesh { get; set; }
        public string Jilla { get; set; }
        public string Gabisa { get; set; }
        public string Ward { get; set; }
        public string Gajjako_sabikthegana { get; set; }
        public string Naksa_sheetno { get; set; }
        public string Kitta_no { get; set; }
        public string Bigga { get; set; }
        public string Kattha { get; set; }
        public string Dhur { get; set; }
        public string Ghar_no { get; set; }
        public string Gharko_prakaar { get; set; }
        public string Gharnirmaan_saal { get; set; }
        public byte[] Files { get; set; }
    }
}
