//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghar_Jagga_Naamsari
    {
        public int FormId { get; set; }
        public string Aabedan_miti { get; set; }
        public string Nibedak_naam { get; set; }
        public string Nibedak_nata { get; set; }
        public string Jagga_Dhaniko_Naam { get; set; }
        public string Mirtyu_miti { get; set; }
        public string Hakdaarko_naam { get; set; }
        public string Mritak_nata { get; set; }
        public string Buwa_patiko_naam { get; set; }
        public string Nagarikta_no { get; set; }
        public string Ghar_no { get; set; }
        public string Kitta { get; set; }
        public string Bigga { get; set; }
        public string Kattha { get; set; }
        public string Dhur { get; set; }
        public string Naksha_sheetno { get; set; }
        public string Kitta_no { get; set; }
        public string Batoko_naam { get; set; }
        public string Batoko_prakar { get; set; }
        public string Ward_no { get; set; }
        public string Kaifiyat { get; set; }
    }
}
