//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jaggadhani_Pratilipi
    {
        public int Form_Id { get; set; }
        public string Aabedan_miti { get; set; }
        public string Naam { get; set; }
        public string Nagarikta_no { get; set; }
        public string Nagarikta_miti { get; set; }
        public string Buwako_naam { get; set; }
        public string Bajeko_naam { get; set; }
        public string Aabedak_pradesh { get; set; }
        public string Aabedak_jilla { get; set; }
        public string Aabedak_gabisa { get; set; }
        public string Aabedak_ward { get; set; }
        public string Aabedak_sabik_thegana { get; set; }
        public string Jaggadhaniko_naam { get; set; }
        public string Kitta_no { get; set; }
        public string Bigga { get; set; }
        public string Kattha { get; set; }
        public string Dhur { get; set; }
        public string Jagga_pradesh { get; set; }
        public string Jagga_jilla { get; set; }
        public string Jagga_gabisa { get; set; }
        public string Jagga_ward { get; set; }
        public string Jagga_sabik_thegana { get; set; }
    }
}
