//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kar_Sambandhi
    {
        public int FormId { get; set; }
        public string Applicated_date { get; set; }
        public string Full_name { get; set; }
        public string Pradesh { get; set; }
        public string Jilla { get; set; }
        public string Gabisa { get; set; }
        public string Ward { get; set; }
        public string Plot_no { get; set; }
        public string Tax_amount { get; set; }
        public string Property_wardno { get; set; }
    }
}
