//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kittakat_Sifaris
    {
        public int FormId { get; set; }
        public string Aabedan_miti { get; set; }
        public string Jagga_Dhaniko_Naam { get; set; }
        public string Chetrafal { get; set; }
        public string Pradesh { get; set; }
        public string Jilla { get; set; }
        public string Gabisa { get; set; }
        public string Ward { get; set; }
        public string Sabik_thegana { get; set; }
        public string Disa { get; set; }
        public string Bigga { get; set; }
        public string Kattha { get; set; }
        public string Dhur { get; set; }
        public string Sheet_no { get; set; }
        public string Kitta_no { get; set; }
        public string Jamma_chetrafal { get; set; }
        public string Bhui_talako_chetrafal { get; set; }
        public string Paune_faar { get; set; }
        public string Karan { get; set; }
        public string Prabidhik_naam { get; set; }
    }
}
