//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Antarik_Basai_Sarai> Antarik_Basai_Sarai { get; set; }
        public virtual DbSet<Asthayi_Basobas> Asthayi_Basobas { get; set; }
        public virtual DbSet<Ghar_Bato_Pramanit> Ghar_Bato_Pramanit { get; set; }
        public virtual DbSet<Ghar_Jagga_Naamsari> Ghar_Jagga_Naamsari { get; set; }
        public virtual DbSet<Ghar_kayamko_sifaris> Ghar_kayamko_sifaris { get; set; }
        public virtual DbSet<Kittakat_Sifaris> Kittakat_Sifaris { get; set; }
        public virtual DbSet<Sthayi_Basobas> Sthayi_Basobas { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
    }
}
