//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nagarikta_Pramanpatra
    {
        public int FormId { get; set; }
        public string Aabedan_miti { get; set; }
        public string karyalaya { get; set; }
        public string Pahilo_naam { get; set; }
        public string Bichko_naam { get; set; }
        public string Thar { get; set; }
        public string First_name { get; set; }
        public string Middle_name { get; set; }
        public string Last_name { get; set; }
        public string Dob { get; set; }
        public string Janma_Pradesh { get; set; }
        public string Janma_Jilla { get; set; }
        public string Janma_Gabisa { get; set; }
        public string Janma_Ward { get; set; }
        public string Janma_Tole { get; set; }
        public string Permanent_Pradesh { get; set; }
        public string Permanent_Jilla { get; set; }
        public string Permanent_Gabisa { get; set; }
        public string Permanent_Ward { get; set; }
        public string Permanent_Tole { get; set; }
        public string Buwako_naam { get; set; }
        public string Buwako_nagariktano { get; set; }
        public string Buwako_Pradesh { get; set; }
        public string Buwako_Jilla { get; set; }
        public string Buwako_Gabisa { get; set; }
        public string Buwako_Ward { get; set; }
        public string Buwako_Tole { get; set; }
        public string Amako_naam { get; set; }
        public string Amako_nagariktano { get; set; }
        public string Amako_Pradesh { get; set; }
        public string Amako_Jilla { get; set; }
        public string Amako_Gabisa { get; set; }
        public string Amako_Ward { get; set; }
        public string Amako_Tole { get; set; }
        public string Patipatniko_naam { get; set; }
        public string Patipatniko_nagariktano { get; set; }
        public string Patipatniko_Pradesh { get; set; }
        public string Patipatniko_Jilla { get; set; }
        public string Patipatniko_Gabisa { get; set; }
        public string Patipatniko_Ward { get; set; }
        public string Patipatniko_Tole { get; set; }
        public string Protector_naam { get; set; }
        public string Protector_Pradesh { get; set; }
        public string Protector_Jilla { get; set; }
        public string Protector_Gabisa { get; set; }
        public string Protector_Ward { get; set; }
        public string Protector_Tole { get; set; }
    }
}
