//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nata
    {
        public int NataId { get; set; }
        public string Nata1 { get; set; }
    }
}
