//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sampati_Muluyankan
    {
        public int FormId { get; set; }
        public string Applicated_date { get; set; }
        public string Full_name { get; set; }
        public string Pradesh { get; set; }
        public string Jilla { get; set; }
        public string Gabisa { get; set; }
        public string Ward { get; set; }
        public string Owners { get; set; }
        public string Particular_plotno { get; set; }
        public string Bigga { get; set; }
        public string Kattha { get; set; }
        public string Dhur { get; set; }
        public string Total_value { get; set; }
        public string Remarks { get; set; }
    }
}
