//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanstha_Darta_Pramanpatra
    {
        public int FormId { get; set; }
        public string Aabedan_miti { get; set; }
        public string Sanstha_naam { get; set; }
        public string Bisayagat_chetra { get; set; }
        public string Darta_no { get; set; }
        public string Darta_miti { get; set; }
        public string Sanstha_pradesh { get; set; }
        public string Sanstha_jilla { get; set; }
        public string Sanstha_gabisa { get; set; }
        public string Sanstha_ward { get; set; }
        public string Sanstha_email { get; set; }
        public string Sanstha_phoneno { get; set; }
        public string Swadesh_bidesh { get; set; }
        public string Karobaar_miti { get; set; }
        public string Sanchalak_naam { get; set; }
        public string Sanchalak_email { get; set; }
        public string Sanchalak_pradesh { get; set; }
        public string Sanchalak_jilla { get; set; }
        public string Sanchalak_gabisa { get; set; }
        public string Sanchalak_ward { get; set; }
        public string Sanchalak_phoneno { get; set; }
        public string ImagePath { get; set; }
    }
}
