//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dainikprashashan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sthayi_Basobas
    {
        public int FormId { get; set; }
        public string Aabedan_miti { get; set; }
        public string Nibedak_naam { get; set; }
        public string Naam { get; set; }
        public string Nagarikta_no { get; set; }
        public string Nagarikta_Jilla { get; set; }
        public string Nagarikta_miti { get; set; }
        public string Pradesh { get; set; }
        public string Jilla { get; set; }
        public string Gabisa { get; set; }
        public string Ward { get; set; }
        public string Sabik_thegana { get; set; }
        public string Basobas_miti { get; set; }
        public string Tole { get; set; }
        public string Batoko_naam { get; set; }
        public string Ghar_no { get; set; }
    }
}
