using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Dainikprashashan.Models
{
    public class GharkayamList
    {
        public int FormId { get; set; }
        public string Aabedan_miti { get; set; }
        public string karyalaya { get; set; }
        public string Aabedak_name { get; set; }
        public string Pradesh { get; set; }
        public string Jilla { get; set; }
        public string Gabisa { get; set; }
        public string Ward { get; set; }
        public string Gajjako_sabikthegana { get; set; }
        public string Naksa_sheetno { get; set; }
        public string Kitta_no { get; set; }
        public string Bigga { get; set; }
        public string Kattha { get; set; }
        public string Dhur { get; set; }
        public string Ghar_no { get; set; }
        public string Gharko_prakaar { get; set; }
        public string Batoko_prakaar { get; set; }
        public string Gharnirmaan_saal { get; set; }
        public byte[] Files { get; set; }
        public string Relationwithapplicant { get; set; }
        public string Partiesname { get; set; }
        public string Annualincome { get; set; }
        public string Remarks { get; set; }
        public string Owner { get; set; }
        public string Anumanitmulya { get; set; }
        public string Particularplotno { get; set; }
        public string TotalValue { get; set; }
        public string Rakam { get; set; }
        public string Naam { get; set; }
        public string Wardno { get; set; }
        public string Nagariktano { get; set; }
        public string Nagariktajilla { get; set; }
        public string Nagariktamiti { get; set; }
        public string Basobasmiti { get; set; }
        public string Sabikthegana { get; set; }
        public string Sabikgabisa { get; set; }
        public string Tole { get; set; }
        public string Haaltole { get; set; }
        public string Batokonaam { get; set; }
        public string Buwakonaam { get; set; }
        public string Amakonaam { get; set; }
        public string Pariwarkonaam { get; set; }
        public string Haalpradesh { get; set; }
        public string Haaljilla { get; set; }
        public string Haalgabisa { get; set; }
        public string Haalward { get; set; }
        public string Nata { get; set; }
        public string Umer { get; set; }
        public string Pahilonaam { get; set; }
        public string Bichkonaam { get; set; }
        public string Thar { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public string Dob { get; set; }
        public string Jarimiti { get; set; }
        public string Nagariktakisim { get; set; }
        public string Janmapradesh { get; set; }
        public string Janmajilla { get; set; }
        public string Janmagabisa { get; set; }
        public string Janmaward { get; set; }
        public string Janmatole { get; set; }
        public string Permanentpradesh { get; set; }
        public string Permanentjilla { get; set; }
        public string Permanentgabisa { get; set; }
        public string Permanentward { get; set; }
        public string Permanenttole { get; set; }
        public string Buwakonagariktano { get; set; }
        public string Buwakopradesh { get; set; }
        public string Buwakojilla { get; set; }
        public string Buwakogabisa { get; set; }
        public string Buwakoward { get; set; }
        public string Buwakotole { get; set; }
        public string Amakonagariktano { get; set; }
        public string Amakopradesh { get; set; }
        public string Amakojilla { get; set; }
        public string Amakogabisa { get; set; }
        public string Amakoward { get; set; }
        public string Amakotole { get; set; }
        public string Patipatnikonaam { get; set; }
        public string Patipatnikonagariktano { get; set; }
        public string Patipatnikopradesh { get; set; }
        public string Patipatnikojilla { get; set; }
        public string Patipatnikogabisa { get; set; }
        public string Patipatnikoward { get; set; }
        public string Patipatnikotole { get; set; }
        public string Protectornaam { get; set; }
        public string Protectorpradesh { get; set; }
        public string Protectorjilla { get; set; }
        public string Protectorgabisa { get; set; }
        public string Protectorward { get; set; }
        public string Protectortole { get; set; }
        public string Bajekonaam { get; set; }
        public string Aabedakpradesh { get; set; }
        public string Aabedakjilla { get; set; }
        public string Aabedakgabisa { get; set; }
        public string Aabedakward { get; set; }
        public string Aabedaksabikthegana { get; set; }
        public string Jaggadhanikonaam { get; set; }
        public string Jaggapradesh { get; set; }
        public string Jaggajilla { get; set; }
        public string Jaggagabisa { get; set; }
        public string Jaggaward { get; set; }
        public string Jaggasabikthegana { get; set; }
        public string Batodisa { get; set; }
        public string Sadaklambai { get; set; }
        public string Sadakchaudai { get; set; }
        public string East { get; set; }
        public string West { get; set; }
        public string North { get; set; }
        public string South { get; set; }
        public string Kaifiyat { get; set; }
        public string Sheetno { get; set; }
        public string Mohikonaam { get; set; }
        public string Sarjaminmiti { get; set; }
        public string Nibedaknaam { get; set; }
        public string Nibedaknata { get; set; }
        public string Mirtyumiti { get; set; }
        public string Hakdaarkonaam { get; set; }
        public string Mritaknata { get; set; }
        public string Buwapatikonaam { get; set; }
        public string Kitta { get; set; }
        public string Chetrafal { get; set; }
        public string Disa { get; set; }
        public string Jammachetrafal { get; set; }
        public string Bhuitalakochetrafal { get; set; }
        public string Paunefaar { get; set; }
        public string Karan { get; set; }
        public string Prabidhiknaam { get; set; }
        public string Sanstha_naam { get; set; }
        public string Bisayagat_chetra { get; set; }
        public string Darta_no { get; set; }
        public string Darta_miti { get; set; }
        public string Sanstha_pradesh { get; set; }
        public string Sanstha_jilla { get; set; }
        public string Sanstha_gabisa { get; set; }
        public string Sanstha_ward { get; set; }
        public string Sanchalak_pradesh { get; set; }
        public string Sanchalak_jilla { get; set; }
        public string Sanchalak_gabisa { get; set; }
        public string Sanchalak_ward { get; set; }
        public string Sanstha_email { get; set; }
        public string Sanstha_phoneno { get; set; }
        public string Swadesh_bidesh { get; set; }
        public string Karobaar_miti { get; set; }
        public string Sanchalak_naam { get; set; }
        public string Sanchalak_email { get; set; }
        public string Sanchalak_phoneno { get; set; }
        public string Byawasaya_naam { get; set; }
        public string Byawasayi_naam { get; set; }
        public string Pan_no { get; set; }
        public string Prakaar { get; set; }
        public string Prakriti { get; set; }
        public string Ghardhaniko_naam { get; set; }
        public string Email { get; set; }
        public string Phoneno { get; set; }
        public string Nikaya { get; set; }
        public string Anya_dartano { get; set; }
        public string Anya_dartamiti { get; set; }
        public string Haalthegana { get; set; }
    public string Byawasaya_Bandamiti { get; set; }

    }
}